version: 2.1
jobs:
  compile:
   docker:
      - image: ubuntu:20.04
   steps:
      - run:
          no_output_timeout: 50m
          command: |
           apt-get -y update && apt-get -y upgrade && DEBIAN_FRONTEND=noninteractive apt-get -y install bc build-essential bison flex zip gcc clang libc6 curl libstdc++6 git wget libssl-dev zstd openjdk-11-jdk openjdk-11-jre
           git clone https://github.com/PREDATOR-project/PREDATOR_kernel_EAS_whyred.git -b predator-eas --depth=1 kernel
           cd kernel
           git clone https://github.com/PREDATOR-project/myscripts.git -b master
           chmod +x myscripts/envsetup.sh
           chmod +x myscripts/circle1.sh
           source ./myscripts/envsetup.sh
           ./myscripts/circle1.sh
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
